kind: Service
apiVersion: v1
metadata:
  name: my-app-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: svc-port 
      port: 80
      targetPort: 80
      nodePort: 30010
